language:
    - python
python:
    - 3.5
install:
    - pip install sphinx sphinx-gallery numpydoc matplotlib pillow nose
script:
    - sphinx-apidoc my_package -o docs/source/
    - cd docs
    - make html
